Repository JorgeArrieta87/skills-connect-the-dots, pull requests merged in 2024-11, with the labels that each got.

#5 Connection
  LICENSE
  README.MD
  README.md
Labels: bug

#8 Create flow.md
  docs/flow.md
Labels: documentation, help wanted

#10 Create CODEOWNERS
  CODEOWNERS
Labels: bug, help wanted
